apiVersion: v1
kind: Pod
metadata:
  name: alpine1
  labels:
    slice_id: "123456"
spec:
  containers:
    - name: alpine
      image: alpine
      command:
        - "/bin/ash"
        - "-c"
        - "sleep 2000"
  nodeSelector:
    kubernetes.io/hostname: master
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  labels:
    slice_id: "123456"
spec:
  containers:
    - name: nginx
      image: nginx
  nodeSelector:
    kubernetes.io/hostname: master
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    slice_id: "123456"
spec:
  containers:
    - name: nginx
      image: nginx
  nodeSelector:
    kubernetes.io/hostname: worker
---

